version: '3.8'
services:
  app:
    build: .
    ports:
      - "9001:9001"
    volumes:
      - .:/app
      - ./models:/app/models
      - ./test_data:/app/test_data
      - ./train:/app/train
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PATH=/app/pig_states.db
    depends_on:
      - db
  db:
    image: sqlite:3
    volumes:
      - ./pig_states.db:/pig_states.db